### PR TITLE
Add smtp_server and smtp_port as configuration variables

### PR DESCRIPTION
**Pull request by christophefromparis**
In order to be able to modify smtp_server and smtp_port via environment variables, I add smtp_server and smtp_port as configuration variables.

### CODE REVIEW

**Comment by DavidGoodwin** [comment]
Would it be possible to allow for ANY postfixadmin variable to be defined through an environment variable - e.g look for any variables with prefix POSTFIXADMIN_xxx and create a $config entry for xxx ?

A bit like https://stackoverflow.com/questions/25765282/bash-loop-through-variables-containing-pattern-in-name perhaps ?

**Comment by J0WI** [comment]
Sure, but it's easier to mount a `config.local.php` into the container than setting a bunch of ENVs, isn't it?

**Comment by J0WI** [comment]
@christophefromparis would be great if you could have a look at https://github.com/postfixadmin/docker/pull/22#pullrequestreview-314641846

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
