### PR TITLE
#24 ADded tzdata package

### LINKED ISSUE #24: Alpine misses the tzdata package and does not handle timezone correctly
The fpm-alpine image misses the tzdata package and does not handle the timezone correctly, leading to inconsistent behavior compared to apache and fpm.

```
docker run --rm -it -e "TZ=Europe/Luxembourg" postfixadmin:fpm date
Fri Mar 27 22:49:49 CET 2020
docker run --rm -it -e "TZ=Europe/Luxembourg" postfixadmin:fpm-alpine date
Fri Mar 27 21:49:56 UTC 2020
```

### PR DESCRIPTION
**Pull request by krufab**
Added tzdata package so that the TZ env variable is handled correctly.

```
docker run --rm -it -e "TZ=Europe/Luxembourg" 2317ceea7eb3 date
Fri Mar 27 22:58:50 CET 2020
docker run --rm -it -e "TZ=Europe/London" 2317ceea7eb3 date
Fri Mar 27 21:58:56 GMT 2020
```

Fixes #24

### CODE REVIEW

**Comment by krufab** [comment]
Resolved conflicts.

**Comment by DavidGoodwin** [comment]
Looks fine to me.... @J0WI ?

**Comment by J0WI** [comment]
IMHO this should be fixed in https://github.com/docker-library/php/pull/949

**Comment by DavidGoodwin** [comment]
ok - then we might as well close this .... with a 'fixed upstream' type comment :) thanks.

**Comment by krufab** [comment]
Pity, I've this mail server set up with nginx, roundcube, postfixadmin and phpmyadmin, and the only image i've to build is this one to add tzdata...
https://github.com/krufab/mailpine/blob/main/apps/web/docker-compose.yml#L44
https://github.com/krufab/mailpine/blob/main/apps/web/pa/Dockerfile

**Pull request closed without merging**
