### PR TITLE
Update to 3.2 and change Apache root

### PR DESCRIPTION
**Pull request by J0WI**
It was a bit tricky to change the root for Apache, so I'm requesting an additional review.

### CODE REVIEW

**Comment by J0WI** [comment]
@DavidGoodwin would be great if you could have a look here.

**Comment by J0WI** [comment]
This might be suboptimal here, because `/var/www/html` is also a docker volume where people can mount the source to.

**Comment by DavidGoodwin** [comment]
I built the apache variant, and it works fine. 
I'm not sure if the entrypoint needs to be 'set -x' though but nevermind.

**Comment by J0WI** [comment]
Thanks!
Btw. are there any known issues with PHP 7.2 or can i bump the version in the container? 7.0 is soon EOL.

**Comment by DavidGoodwin** [comment]
I'm not aware of anything... bump away.

**Pull request merged**
