### PR TITLE
Added support for $CONF['encrypt'] with POSTFIXADMIN_PASSWD_ENCRYPTION

### PR DESCRIPTION
**Pull request by BOFH90**
Added the environment variable for this Issue:
https://github.com/postfixadmin/docker/issues/20

### CODE REVIEW

**Comment by DavidGoodwin** [comment]
I'd almost prefer it that your new env var ( POSTFIXADMIN_PASSWD_ENCRYPTION ) was called POSTFIXADMIN_ENCRYPT - 'cos at least then there's a direct mapping to the $CONF variable name, but I can see why you chose a different name.

Alternatively, we look at some way of having a directory of config file(s) that can be added in - so rather than needing to support 101 environment variables, you just mount  PHP config file(s) into the container?

**Comment by BOFH90** [comment]
Sure, I can rename the env var to "POSTFIXADMIN_ENCRYPT" if you´d like to. Your suggestion to add config-files also sounds fine to me.

**Comment by BOFH90** [comment]
UPDATED: Changed env var name to POSTFIXADMIN_ENCRYPT

**Comment by DavidGoodwin** [comment]
Thanks for the PR - sorry - I've not been paying attention to the 'docker' repo - so this has sat unloved for a short while.

Anyway - looks good to me.....

**Pull request merged**
