### PR TITLE
dkim enviroment variable

### PR DESCRIPTION
**Pull request by ramank775**

### CODE REVIEW

**Comment by DavidGoodwin** [comment]
LGTM; thank you for contributing

**Comment by ramank775** [comment]
@DavidGoodwin can you please guide me on what required to merge it?

**Comment by DavidGoodwin** [comment]
@ramank775 I was hoping @J0WI would do that ... but I can....

**Comment by DavidGoodwin** [comment]
(I'm not sure what magic needs to be done to publish newer docker images though)

**Pull request merged**
